AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  VTApiKey:
    Type: String
    NoEcho: true

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-north-1:609356923180:userpool/eu-north-1_LvyjwoWyM
            Identity:
              Header: Authorization

  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetGameFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        GetGame:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game/{Slug}
            Method: get

  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetGamesFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:ScanItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        GetGames:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: get
  
  GetModsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetModsFunction
      Environment:
        Variables:
          BUCKET: moddatabucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/ThumbnailTable
      Events:
        GetMods:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{Game}/mods
            Method: get

  GetModFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetModFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/MainModTable
      Events:
        GetMod:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{Game}/{modId}
            Method: get

  GetVersionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetVersionsFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/MainModTable
      Events:
        GetVersions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{Game}/{modId}/versions
            Method: get

  DeleteGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/DeleteGameFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        DeleteGame:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer

  AddGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/AddGameFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        AddGame:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
  
  AddUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/AddUserFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/UserTable

  AddModFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/AddModFunction
      Timeout: 600
      MemorySize: 2048
      Environment:
        Variables:
          BUCKET: moddatabucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/MainModTable
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::moddatabucket/*
      Events:
        AddMod:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game/upload
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
          
  DownloadVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/DownloadVersionFunction
      Environment:
        Variables:
          BUCKET: moddatabucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - arn:aws:s3:::moddatabucket/*
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/MainModTable
      Events:
        DownloadVersion:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{Game}/{modId}/{version}/download
            Method: get
  
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: src/ImageProcessorFunction
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET: moddatabucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - arn:aws:s3:::moddatabucket/*
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/MainModTable
                - arn:aws:dynamodb:eu-north-1:609356923180:table/ThumbnailTable
  
  VirusCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: src/VirusCheckFunction
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          VT_API_KEY: !Ref VTApiKey
          BUCKET: moddatabucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::moddatabucket/*
        - DynamoDBCrudPolicy:
            TableName: MainModTable
  
  AllowS3InvokeVirusScanner:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: VirusCheckFunction
      Action:
        lambda:InvokeFunction
      Principal:
        s3.amazonaws.com
      SourceArn:
        arn:aws:s3:::moddatabucket

  AllowS3InvokeImageProcessor:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ImageProcessorFunction
      Action:
        lambda:InvokeFunction
      Principal:
        s3.amazonaws.com
      SourceArn:
        arn:aws:s3:::moddatabucket