AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-north-1:609356923180:userpool/eu-north-1_NmMwkSTUS
            Identity:
              Header: Authorization

  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/GetGamesFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:ScanItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        GetGames:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: get


  DeleteGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/DeleteGameFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        DeleteGame:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer


  AddGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/AddGameFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/GamesTable
      Events:
        AddGame:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /Game
            Method: post
  
  AddUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AddUserFunction
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/AddUserFunction
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - arn:aws:dynamodb:eu-north-1:609356923180:table/UserTable