name: Deploy SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - uses: aws-actions/setup-sam@v2

      - name: Build
        run: sam build

      - name: Deploy
        run: |
          sam deploy \
            --stack-name modsharingplatform-api \
            --region eu-north-1 \
            --s3-bucket sam-artifacts-modsharingplatform \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Allow Cognito to invoke Lambda
        run: |
          LAMBDA_ARN=$(aws lambda list-functions \
            --query "Functions[?contains(FunctionName, 'modsharingplatform-api-AddUserFunction')].FunctionArn" \
            --output text)

          echo "Using Lambda: $LAMBDA_ARN"

          aws lambda add-permission \
            --function-name "$LAMBDA_ARN" \
            --statement-id CognitoPostConfirmation \
            --action lambda:InvokeFunction \
            --principal cognito-idp.amazonaws.com \
            --source-arn arn:aws:cognito-idp:eu-north-1:609356923180:userpool/eu-north-1_NmMwkSTUS || echo "Permission already exists"


      - name: Attach Cognito Post Confirmation Trigger
        run: |
          LAMBDA_ARN=$(aws lambda list-functions \
            --query "Functions[?contains(FunctionName, 'modsharingplatform-api-AddUserFunction')].FunctionArn" \
            --output text)

          echo "Attaching Cognito trigger to: $LAMBDA_ARN"

          aws cognito-idp update-user-pool \
            --user-pool-id eu-north-1_NmMwkSTUS \
            --lambda-config PostConfirmation=$LAMBDA_ARN