name: Deploy src/AddGameFunction

on:
  push:
    paths:
      - "src/AddGameFunction/**"
    branches: [main]

env:
    LAMBDA_NAME: AddGameFunction
    LAMBDA_DIR: src/AddGameFunction
    LAMBDA_FILENAME: index

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Create zip file for Lambda function
        working-directory: ${{ env.LAMBDA_DIR }}
        run: zip -r ${{ env.LAMBDA_FILENAME }}.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_NAME }} \
            --zip-file fileb://${{ env.LAMBDA_DIR }}/${{ env.LAMBDA_FILENAME }}.zip

      - name: Verify deployment
        run: |
          aws lambda get-function \
            --function-name ${{ env.LAMBDA_NAME }}